#!/bin/bash

mkdir output
mkdir output/style
mkdir output/fonts
mkdir output/html
mkdir output/fonts/Serif
mkdir output/fonts/Typewriter

cp fonts/Serif/cmunrm.woff output/fonts/Serif/
cp fonts/Typewriter/cmuntt.woff output/fonts/Typewriter/
cp -r res output

# stylesheets

cp style/fonts.css output/style
echo "copying scss files..."
for scss in style/*.scss
do
    CSS=output/"${scss%.scss}.css"
    sass $scss $CSS

    if [ $scss != *"colors.scss"* ] && [ $scss != *"Light.scss"* ];
    then
        LIGHT="${scss%.scss}Light.scss"
        cp -v $scss $LIGHT

        sed -i 's/base03/base3/g' $LIGHT
        sed -i 's/base2/base02/g' $LIGHT

        # generate css
        echo "generating light stylesheets"
        LIGHTCSS=output/"${LIGHT%.scss}.css"
        sass $LIGHT $LIGHTCSS
        rm $LIGHT
    fi
done

# html pages
for html in html/*.html
do
    htmlDark="${html/html/output}"
    cp $html $htmlDark

    if [ $html != *"Light.html"* ];
    then
        LIGHT="${htmlDark%.html}Light.html"
        cp -v $htmlDark $LIGHT

        # fill templates
        sed -e '/##headDefault##/ {' -e 'r html/templates/headDefault' -e 'd' -e '}' -i $LIGHT
        sed -e '/##headDefault##/ {' -e 'r html/templates/headDefault' -e 'd' -e '}' -i $htmlDark
        sed -e '/##menuButtons##/ {' -e 'r html/templates/menuButtons' -e 'd' -e '}' -i $LIGHT
        sed -e '/##menuButtons##/ {' -e 'r html/templates/menuButtons' -e 'd' -e '}' -i $htmlDark

        sed -i 's/Light.html/tmpIL/g' $LIGHT

        sed -i 's/index.html/indexLight.html/g' $LIGHT
        sed -i 's/studies.html/studiesLight.html/g' $LIGHT
        sed -i 's/work.html/workLight.html/g' $LIGHT
        sed -i 's/about.html/aboutLight.html/g' $LIGHT
        sed -i 's/contact.html/contactLight.html/g' $LIGHT
        sed -i 's/style.css/styleLight.css/g' $LIGHT

        sed -i 's/tmpIL/.html/g' $LIGHT
        sed -i 's/btnLight/btnDark/g' $LIGHT
        sed -i 's/lineDark/lineLight/g' $LIGHT
    fi
done

rm output/style/*.css.map
