#!/bin/bash

mkdir output
mkdir output/style
mkdir output/html

cp -r fonts output

# stylesheets

cp style/fonts.css output/style
echo "copying scss files..."
for scss in style/*.scss
do
    CSS=output/"${scss%.scss}.css"
    sass $scss $CSS

    if [ $scss != *"colors.scss"* ] && [ $scss != *"Light.scss"* ];
    then
    LIGHT="${scss%.scss}Light.scss"
    cp -v $scss $LIGHT

    sed -i 's/base03/base3/g' $LIGHT
    sed -i 's/base2/base02/g' $LIGHT

    # generate css
    echo "generating light stylesheets"
    LIGHTCSS=output/"${LIGHT%.scss}.css"
    sass $LIGHT $LIGHTCSS
    rm $LIGHT
    fi
done

# html pages
for html in html/*.html
do
    cp $html output/$html
    if [ $html != *"Light.html"* ];
    then
        LIGHT=output/"${html%.html}Light.html"
        cp -v $html $LIGHT
    sed -i 's/style.css/styleLight.css/g' $LIGHT
    sed -i 's/Light.html/.html/g' $LIGHT
    sed -i 's/btnLight/btnDark/g' $LIGHT
    fi
done

rm output/style/*.css.map
